#!/bin/bash

. /usr/sbin/so-common

ELASTICDIR="/opt/elastic"
mkdir -p $ELASTICDIR
cd $ELASTICDIR
PCAP_DIR="$ELASTICDIR/pcap"

GITREPO="elastic-test"
GITURL="https://github.com/Security-Onion-Solutions/$GITREPO.git"
DOCKERHUB="securityonionsolutions"
if [ "$1" == "dev" ]; then
	GITURL="https://github.com/dougburks/$GITREPO.git"
	DOCKERHUB="dougburks"
fi

CONF="/etc/nsm/securityonion.conf"
if ! grep "# Elastic Download" $CONF >/dev/null 2>&1; then
cat << EOF >> $CONF

# Elastic Download
GITREPO="$GITREPO"
GITURL="$GITURL"
DOCKERHUB="$DOCKERHUB"
EOF
fi

[ -f $CONF ] && . $CONF
