#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run using sudo!"
        exit 1
fi

docker stats so-elasticsearch so-logstash so-kibana so-elastalert so-curator so-freqserver so-domainstats $@
