#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

echo "Stopping containers:"
[ "$LOGSTASH_ENABLED" = "yes" ] && docker stop so-logstash
[ "$KIBANA_ENABLED" = "yes" ] && docker stop so-kibana
[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker stop so-elasticsearch
[ "$ELASTALERT_ENABLED" = "yes" ] && docker stop so-elastalert
[ "$CURATOR_ENABLED" = "yes" ] && docker stop so-curator
[ "$FREQ_SERVER_ENABLED" = "yes" ] && docker stop so-freqserver
[ "$DOMAIN_STATS_ENABLED" = "yes" ] && docker stop so-domainstats
