#!/bin/bash

. /usr/sbin/so-elastic-common
. /etc/nsm/securityonion.conf

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

# List indices
echo
curl -XGET "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/_cat/indices?v&pretty"
echo

# Inform user we are about to delete all data
echo
echo "This script will delete all data (documents, indices, etc.) in the Elasticsearch database."
echo
echo "If you would like to proceed, please type "AGREE" and hit ENTER."
echo

# Read user input
read INPUT
if [ "$INPUT" != "AGREE" ] ; then exit 0; fi

# Stop syslog-ng
echo
service syslog-ng stop
echo

# Delete data
echo "Deleting data..."
curl -XDELETE "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/logstash-*" > /dev/null 2>&1

# Start syslog-ng
echo
service syslog-ng start
echo

# Message to user
echo
echo "All Elasticsearch data has been deleted."
echo
