#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run using sudo!"
        exit 1
fi

source /etc/nsm/securityonion.conf

echo "Removing existing containers:"
[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker rm so-elasticsearch
[ "$LOGSTASH_ENABLED" = "yes" ] && docker rm so-logstash
[ "$KIBANA_ENABLED" = "yes" ] && docker rm so-kibana
