#!/bin/bash

. /usr/sbin/so-elastic-common

. /usr/sbin/so-elastic-download-pcaps

header "Installing libapache2-mod-authnz-external"
apt-get install -y libapache2-mod-authnz-external > /dev/null
echo "Done!"

header "Installing Docker"
cp $SRC/etc/apt/preferences.d/securityonion-docker /etc/apt/preferences.d/
apt-get -y install apt-transport-https ca-certificates curl > /dev/null
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"
apt-get update > /dev/null
apt-get -y install docker-ce > /dev/null
echo "Done!"

header "Enabling DOCKER_CONTENT_TRUST"
echo "export DOCKER_CONTENT_TRUST=1" >> /etc/profile.d/securityonion-docker.sh
export DOCKER_CONTENT_TRUST=1
echo "Done!"

header "Downloading Docker containers"
for i in so-elasticsearch so-kibana so-logstash so-elastalert so-curator so-freqserver so-domainstats; do
	docker pull --disable-content-trust=false $DOCKERHUB/$i
done
echo "Done!"
