#!/bin/bash

. /usr/sbin/so-common

DIR="/opt/elastic"
mkdir -p $DIR
cd $DIR
PCAP_DIR="$DIR/pcap"

REPO="elastic-test"
if [ "$1" == "dev" ]; then
        URL="https://github.com/dougburks/$REPO.git"
        DOCKERHUB="dougburks"
else
        URL="https://github.com/Security-Onion-Solutions/$REPO.git"
        DOCKERHUB="securityonionsolutions"
fi
