#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

header "Configuring Kibana dashboards"

# Check to see if Elasticsearch is available
max_wait=240
until curl -s -XGET http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/_cluster/health > /dev/null ; do
	wait_step=$(( ${wait_step} + 1 ))
	if [ ${wait_step} -gt ${max_wait} ]; then
		echo "ERROR: elasticsearch server not available for more than ${max_wait} seconds."
		exit 5
	fi
	sleep 1s;
done

# Load dashboards, visualizations, index pattern(s), etc.
cd $SRC/kibana/dashboards/
sh load.sh
cd $ELASTICDIR
