#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

# Publish ports to localhost 127.0.0.1 ONLY
if [ "$ELASTICSEARCH_ENABLED" = "yes" ]; then
        echo -n "so-elasticsearch: "

        if docker ps | grep -q so-elasticsearch; then
                echo "Already started!"
        else
                docker run --name=so-elasticsearch \
                        --detach \
                        --env "bootstrap.memory_lock=true" \
                        --env "cluster.name=$HOSTNAME" \
                        --env ES_JAVA_OPTS="-Xms$ELASTICSEARCH_HEAP -Xmx$ELASTICSEARCH_HEAP" \
                        --env "http.host=0.0.0.0" \
                        --env "transport.host=127.0.0.1" \
                        --publish 127.0.0.1:9200:9200 \
                        --publish 127.0.0.1:9300:9300 \
                        --ulimit memlock=-1:-1 \
                        --ulimit nofile=65536:65536 \
                        --ulimit nproc=2048 \
                        --volume /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro \
                        --volume /etc/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro \
                        --volume /nsm/elasticsearch:/usr/share/elasticsearch/data \
                        --volume /var/log/elasticsearch:/var/log/elasticsearch \
                        $ELASTICSEARCH_OPTIONS \
                        $DOCKERHUB/so-elasticsearch
                        docker network connect --alias elasticsearch $DOCKERNET so-elasticsearch
        fi
fi
