#!/bin/bash
#
# This script is used to wipe all indices/data from Elasticsearch
#
# List indices.
echo
curl -XGET 'localhost:9200/_cat/indices?v&pretty'
echo

# Inform user we are about to delete all data.
echo
echo "This script will delete all data (documents, indices, etc.) in the Elasticsearch database."
echo
echo "If you would like to proceed, please type "AGREE" and hit ENTER."
echo

# Read user input
read INPUT
if [ "$INPUT" != "AGREE" ] ; then exit 0; fi

# Stop syslog-ng
echo
service syslog-ng stop
echo

# Delete data.
echo "Deleting data..."
curl -XDELETE 'localhost:9200/logstash-*' > /dev/null 2>&1

# Start syslog-ng
echo
service syslog-ng start
echo

# Mesage to user
echo
echo "All Elasticsearch data has been deleted."
echo
