#!/bin/bash

. /usr/sbin/so-elastic-common

SOCONF="/etc/nsm/securityonion.conf"
ELASTICONF="$SRC/etc/securityonion-elastic.conf"

#Specify Docker network and create it
header "Creating Docker network for Elastic Stack"
DOCKERNET=`grep 'DOCKERNET' $ELASTICONF | cut -d "=" -f2 | sed 's/"//g'`
if pgrep -f docker > /dev/null; then
        docker network create $DOCKERNET --driver=bridge >/dev/null 2>&1
        echo $DOCKERNET
fi

header "Setting vm.max_map_count to 262144"
sysctl -w vm.max_map_count=262144
cp $SRC/etc/sysctl.d/* /etc/sysctl.d/
echo "Done!"

header "Configuring users"
UID_GID=930
for USER in elasticsearch logstash kibana elastalert curator freqserver domainstats; do
        if grep -q $USER /etc/group; then
                echo "Group $USER already exists!"
        else
                echo "Creating $USER group..."
                groupadd --gid $UID_GID $USER
        fi
        if [ `id -u $USER` ]; then
                echo "User $USER already exists!"
        else
                echo "Creating $USER user..."
                useradd --uid $UID_GID --gid $UID_GID --home-dir /home/$USER --no-create-home $USER
        fi
        let UID_GID=UID_GID+1
done

header "Configuring ElasticSearch"
mkdir -p /etc/elasticsearch
mkdir -p /nsm/elasticsearch
mkdir -p /var/log/elasticsearch
chown -R elasticsearch:elasticsearch /nsm/elasticsearch
chown -R elasticsearch:elasticsearch /var/log/elasticsearch
touch /etc/nsm/crossclustertab
chown elasticsearch:elasticsearch /etc/nsm/crossclustertab 
cp -av $SRC/etc/elasticsearch/* /etc/elasticsearch/
if [ -f /etc/elasticsearch/elasticsearch.yml ]; then
        sed -i "s/cluster\.name.*/cluster\.name: \"$HOSTNAME\"/" /etc/elasticsearch/elasticsearch.yml
fi
echo "Done!"

header "Configuring Logstash"
mkdir -p /nsm/logstash
mkdir -p /var/log/logstash
mkdir -p /etc/logstash/conf.d/
mkdir -p /etc/logstash/optional/
chown -R logstash:logstash /nsm/logstash
chown -R logstash:logstash /var/log/logstash
cp -av $SRC/configfiles/*.conf /etc/logstash/conf.d/
cp -av $SRC/configfiles-setup_required/8*_postprocess_dns_*.conf /etc/logstash/optional/
cp -av $SRC/configfiles-setup_required/85*_postprocess_freq_analysis_*.conf /etc/logstash/optional/
cp -av $SRC/configfiles/*.conf /etc/logstash/conf.d/
cp -av $SRC/etc/logstash/* /etc/logstash/
cp -av $SRC/lib/dictionaries /lib/
#cp -rf $SRC/grok-patterns /lib/
echo "Done!"

header "Configuring Kibana"
mkdir -p /etc/kibana
mkdir -p /var/log/kibana
chown -R kibana:kibana /etc/kibana
chown -R kibana:kibana /var/log/kibana
cp -av $SRC/etc/kibana/* /etc/kibana/
echo "Done!"

header "Configuring Elastalert"
mkdir -p /etc/elastalert/rules
mkdir -p /var/log/elastalert
chown -R elastalert:elastalert /etc/elastalert/rules
chown -R elastalert:elastalert /var/log/elastalert
cp -av $SRC/etc/elastalert/rules/* /etc/elastalert/rules/
echo "Done!"

header "Configuring Curator"
mkdir -p /etc/curator/config
mkdir -p /etc/curator/action
mkdir -p /var/log/curator
chown -R curator:curator /etc/curator
chown -R curator:curator /var/log/curator
cp -av $SRC/etc/curator/config/* /etc/curator/config/
cp -av $SRC/etc/curator/action/* /etc/curator/action/
echo "Done!"

header "Configuring freq_server"
mkdir -p /var/log/freq_server
mkdir -p /var/log/freq_server_dns
chown -R freqserver:freqserver /var/log/freq_server
echo "Done!"

header "Configuring domain_stats"
mkdir -p /var/log/domain_stats
mkdir -p /var/log/domain_stats
chown -R domainstats:domainstats /var/log/domain_stats
echo "Contacting WHOIS server for connectivity..."
echo
# Check for whois connectivity
whois google.com | grep 'Domain Name'
if [ $? -eq 1 ]; then
        echo
        echo "Unable to reach WHOIS server...disabling DomainStats"
        DS_ENABLED="no"
else
        DS_ENABLED="yes"
fi
echo "Done!"

ELSA=NO
[ -f /etc/nsm/securityonion.conf ] && . /etc/nsm/securityonion.conf
if [ $ELSA == "YES" ];then
        . /usr/sbin/so-elastic-configure-log-size
fi

header "Adding Elastic Stack options to $SOCONF"
while read EACH_LINE; do
        OPTION=$(echo $EACH_LINE | cut -d'=' -f1)
        if ! grep -q "$OPTION" $SOCONF; then
                if echo "$EACH_LINE" | grep -q '#'; then
                        echo >> $SOCONF
                fi
        echo "$EACH_LINE" >> $SOCONF
        fi
done < $ELASTICONF

if [ "$DS_ENABLED" == "no" ]; then
        sed -i 's/^DOMAIN_STATS_ENABLED.*/DOMAIN_STATS_ENABLED="no"/' $SOCONF
else
        if [ "$DS_ENABLED" == "yes" ]; then
                sed -i 's/^DOMAIN_STATS_ENABLED.*/DOMAIN_STATS_ENABLED="yes"/' $SOCONF
        fi
fi

# Get total installed memory
TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}' | sed -r 's/.{3}$//'`

# If total memory is less than 8GB, we keep the default of 600m for heap size
if [ $TOTAL_MEM -lt 8000 ] ; then
        ES_HEAP_SIZE="600m"
        LS_HEAP_SIZE="1g"
elif [ $TOTAL_MEM -ge 124000 ]; then
        # Set a max of 31GB for heap size
        # https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
        ES_HEAP_SIZE="31000m"
        LS_HEAP_SIZE="$ES_HEAP_SIZE"
else
        # Set heap size to 25% of available memory
        ES_HEAP_SIZE=$(($TOTAL_MEM / 4))"m"
        LS_HEAP_SIZE="$ES_HEAP_SIZE"
fi

sed -i "s/ELASTICSEARCH_HEAP.*/ELASTICSEARCH_HEAP=\"$ES_HEAP_SIZE\"/" $SOCONF
sed -i "s/LOGSTASH_HEAP.*/LOGSTASH_HEAP=\"$LS_HEAP_SIZE\"/" $SOCONF

echo "Done!"

header "Starting Elastic Stack"
chmod +x /usr/sbin/so-elastic-*
/usr/sbin/so-elastic-start
echo "Done!"

header "Configuring Elastic Stack to start on boot"
cp $SRC/etc/init/securityonion.conf /etc/init/securityonion.conf
echo "Done!"
