#!/bin/bash

. /usr/sbin/so-elastic-common

for FILE in /etc/nsm/securityonion.conf /etc/nsm/sensortab; do
	if [ ! -f $FILE ]; then
		echo "$FILE not found!  Exiting!"
		exit 1
	fi
done

. /usr/sbin/so-elastic-configure-stack

. /usr/sbin/so-elastic-configure-apache

. /usr/sbin/so-elastic-configure-disable-elsa

. /usr/sbin/so-elastic-configure-kibana-shortcuts

. /usr/sbin/so-elastic-configure-syslog-ng

. /usr/sbin/so-elastic-configure-ossec-rules

cd $ELASTICDIR

. /usr/sbin/so-elastic-configure-kibana

. /usr/sbin/so-elastic-configure-curator

. /usr/sbin/so-elastic-configure-elastalert

. /usr/sbin/so-elastic-configure-cron

echo
echo "All Done!"
