#!/bin/bash

# Check for prerequisites
if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run using sudo!"
        exit 1
fi

# Make a directory to store downloads
DIR="/opt/elastic"
mkdir -p $DIR
cd $DIR
PCAP_DIR="$DIR/pcap"

# Define a banner to separate sections
banner="========================================================================="

header() {
        echo
        printf '%s\n' "$banner" "$*" "$banner"
}

REPO="elastic-test"
if [ "$1" == "dev" ]; then
        URL="https://github.com/dougburks/$REPO.git"
        DOCKERHUB="dougburks"
else
        URL="https://github.com/Security-Onion-Solutions/$REPO.git"
        DOCKERHUB="securityonionsolutions"
fi
