#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run using sudo!"
        exit 1
fi

source /etc/nsm/securityonion.conf

echo "Stopping containers:"
[ "$LOGSTASH_ENABLED" = "yes" ] && docker stop so-logstash
[ "$KIBANA_ENABLED" = "yes" ] && docker stop so-kibana
[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker stop so-elasticsearch
[ "$ELASTALERT_ENABLED" = "yes" ] && docker stop so-elastalert
