#!/bin/bash

source /etc/nsm/securityonion.conf

echo "Stopping containers:"
[ "$LOGSTASH_ENABLED" = "yes" ] && docker stop so-logstash
[ "$KIBANA_ENABLED" = "yes" ] && docker stop so-kibana
[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker stop so-elasticsearch
