#!/bin/bash

. /usr/sbin/so-elastic-common

header "Replaying pcaps to create new logs for testing"
INTERFACE=`grep -v "^#" /etc/nsm/sensortab | head -1 | awk '{print $4}'`
for i in /opt/samples/*.pcap /opt/samples/markofu/*.pcap /opt/samples/mta/*.pcap $PCAP_DIR/*.trace $PCAP_DIR/*.pcap; do
	echo -n "." 
	tcpreplay -i $INTERFACE -M10 $i >/dev/null 2>&1
done
echo
