#!/bin/bash
SOCONF="/etc/nsm/securityonion.conf"

header "Migrating ELSA log_size_limit value"
LOG_SIZE_LIMIT=$(grep 'log_size_limit' /etc/elsa_node.conf | cut -d: -f2 | sed 's/ //' | sed 's/,//')
LOG_SIZE_LIMIT_GB=$(($LOG_SIZE_LIMIT/1000000000))
if ! grep -q LOG_SIZE_LIMIT $SOCONF; then
        cat << EOF >> $SOCONF

# Log size limit (GB) for Elasticsearch logs
LOG_SIZE_LIMIT=$LOG_SIZE_LIMIT_GB
EOF
else
        sed "s/LOG_SIZE_LIMIT=.*/LOG_SIZE_LIMIT=$LOG_SIZE_LIMIT_GB/" $SOCONF
fi
echo "Done!"
