#!/bin/bash

. /usr/sbin/so-common

. /etc/nsm/securityonion.conf

echo
header "Restarting NSM services..."
echo

service nsm restart

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

echo
header "Restarting Elastic stack..."
echo

/usr/sbin/so-elastic-restart
