#!/bin/bash

. /usr/sbin/so-elastic-common

. /usr/sbin/so-replay

. /usr/sbin/so-elastic-download

header "Processing final ELSA buffers"
sh /opt/elsa/contrib/securityonion/contrib/securityonion-elsa-cron.sh
sh /opt/elsa/contrib/securityonion/contrib/securityonion-elsa-cron.sh

. /usr/sbin/so-elastic-configure

SECONDS=60
header "Waiting $SECONDS seconds to allow Logstash to initialize"
for i in `seq 1 $SECONDS`; do
        sleep 1s
        echo -n "."
done
echo

header "Running experimental ELSA migration script"
/usr/sbin/so-migrate-elsa-data-to-elastic -y

. /usr/sbin/so-test

. /usr/sbin/so-elastic-final-text
